### ISSUE TITLE
Need a whitespace after `payload.review.state`

### ISSUE THREAD

**Issue by yasulab** [idobata/idobata-hooks#97]
PR 送ろうと思ったんですがどこを直すと良さそうなのかパッと見てわからなかったので Issue で失礼します 🙇 

## 半角の空白スペースが必要な部分の例

![image](https://user-images.githubusercontent.com/155807/54097806-1d5a0c80-43f5-11e9-9abc-89e1e8a30f5b.png)

cf. https://idobata.io/#/organization/yasslab/room/railsguides-public-news?query=approved%20pull%20request

## たぶんココを直すと良さそう...? 🤔💭

.oO(多分ココのどこかを直すと良さそうというところまではわかったんですが... 😅 )

https://github.com/idobata/idobata-hooks/blob/master/lib/hooks/github/templates/pull_request_review.html.haml

**Comment by hibariya** [comment]
@yasulab ありがとうございます! おっしゃる通りその辺りを修正すると良さそうです :smile: みてみますー

**Comment by hibariya** [comment]
さきほど idobata.io へ修正を反映しました。
@yasulab 共有ありがとうございました :pray:

**Comment by yasulab** [comment]
早速のご対応ありがとうございます...!! 😻🆒✨
